Fixes for OpenCV imshow Functionality and Dependency Issues (#13)
* Removed unused files.

* Updated base image of Dockerfile to use PyTorch 24.08.

* Use `opencv-python` package on PyPI instead of the `python3-opencv` package in the Ubuntu distribution to resolve the following error:
```
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py",
    line 361, in <module>
        from torch._C import *  # noqa: F403
        ImportError: /opt/hpcx/ucc/lib/libucc.so.1: undefined symbol:
        ucs_config_doc_nop
```

* Fixed the issue with OpenCV's imshow to work.
  * Fixed an issue where the version of OpenCV shows 4.7.0 rather than the newly installed 4.10.0, even after removing the `opencv` package in the base image. 
  * Install the `libgl1-mesa-glx` package to resolve the following error:
```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

  * Install the `x11-utils` package to resolve the following error:
```
>>> cv2.imshow('abc', np.zeros((2,2)))
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.10/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```